### ISSUE TITLE
Bug, application without text

### ISSUE THREAD

**Issue by kolpakov777** [Bene2103/HaaConfigurator#1]
Maybe I don't have enough fonts, or additional libraries, but the application window looks like this.
Can I fix it myself?
![image](https://user-images.githubusercontent.com/48173672/236855623-c32c8851-e9fd-4a5c-998e-ecea340c8b5d.png)

**Comment by Bene2103** [comment]
I've seen this one time before, but i really dont know whats causing this to happen. I tried the app on multiple PC's but i never saw this in person.

Have you installed the .net framework from the first release?

**Comment by kolpakov777** [comment]
Yes, I installed .net framework

**Comment by kolpakov777** [comment]
Is it possible to compile this wonderful application for macos?

**Comment by kolpakov777** [comment]
Microsoft net also gives an error at startup with the following debugging data. Maybe it will help in debugging:

System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at HAA_Configurator.TestProgramm.generate_haa()
   at HAA_Configurator.TestProgramm.TestProgramm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded assemblies **************
System.Private.CoreLib
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Private.CoreLib.dll
----------------------------------------
HAA_Configurator
    Build version: 1.0.0.0
    Win32 version: Not applicable
    CodeBase: 
----------------------------------------
System.Runtime
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.dll
----------------------------------------
System.Drawing.Common
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Build version: 4.0.0.0
    Win32 version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Memory
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Memory.dll
----------------------------------------
System.Numerics.Vectors
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Numerics.Vectors.dll
----------------------------------------
System.ObjectModel
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ObjectModel.dll
----------------------------------------
System.Private.Uri
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Private.Uri.dll
----------------------------------------
System.ComponentModel
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.dll
----------------------------------------
System.Resources.Extensions
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Drawing.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.Loader
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/ru/System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Build version: 7.0.0.0
    Win32 version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.Immutable.dll
----------------------------------------

**Comment by Bene2103** [comment]
Sorry i cannot see why it doesnt work.

But i have compiled a new version for x86_64 instead of x86, maybe this does the trick.
I've released v0.16 if you wanna try

MacOS isnt a priority, because i primarily work on windows.

**Comment by kolpakov777** [comment]
The new version also does not work and gives an error during startup. I tried it on another computer, the result is the same.

**Comment by Bene2103** [comment]
Just a quick question, do you have a cyrillic display language?
The other guy with this problem had cyrillic language and the exact same problem.

Maybe you can try this programm on a pc without cyrillic display language?

**Comment by kolpakov777** [comment]
Yes, both computers have the "Russian" language installed on the system. Unfortunately, it is not possible to check on another system without Cyrillic.

**Comment by Bene2103** [comment]
So i tried it myself in a virtual machine with russian windows 10, same error as you showed me.
I released a new version which should now work fine, at least on my machine it does.

![image](https://github.com/Bene2103/HaaConfigurator/assets/46553509/e342b401-0964-4f70-bdbb-a44786a327b5)

Please try it out and let me know if it works!

**Comment by kolpakov777** [comment]
Yes, now your delightful creation works! You're amazing!

**Comment by kolpakov777** [comment]
The problem is solved!

**Comment by sercitecotf** [comment]
Could it also work the other way around, if we put the meplhaa in it and it automatically fills in the values of the boxes?

**Comment by kolpakov777** [comment]
Let it work!

**Comment by Bene2103** [comment]
Good to hear that it works for you!  

Now i can focus again on adding features :-)

**Comment by Bene2103** [comment]
> Could it also work the other way around, if we put the meplhaa in it and it automatically fills in the values of the boxes?

First i want to finish the actual functions of the program, so that anyone can create json configs.
If all features are working, than we can talk about more features.

**Comment by kolpakov777** [comment]
> > Could it also work the other way around, if we put the meplhaa in it and it automatically fills in the values of the boxes?
> 
> First i want to finish the actual functions of the program, so that anyone can create json configs. If all features are working, than we can talk about more features.

You did a great job!
